/**
 * Shift Types Module
 * 
 * Contains TypeScript interfaces for shift management functionality.
 * Defines the structure for shift requirements, assignments, and schedules.
 * These types are used throughout the application for type safety and
 * consistent data handling.
 * 
 * @module
 */

/**
 * Represents a shift requirement for a specific day and time
 * @interface
 * @property {string} id - Unique identifier for the shift requirement
<<<<<<< HEAD
 * @property {string} name - Name of the shift requirement
=======
>>>>>>> 814f5aa8e56d545825b7fd94a72c02dc721cc589
 * @property {number} day_of_week - Day of the week (0-6, where 0 is Sunday)
 * @property {string} start_time - Start time in HH:mm format
 * @property {string} end_time - End time in HH:mm format
 * @property {number} required_count - Number of employees required for this shift
 */
export interface ShiftRequirement {
  id: string
  name: string
  day_of_week: number
  start_time: string
  end_time: string
  required_count: number
}

/**
 * Form data structure for creating/updating shift requirements
 * Omits the id field as it's generated by the database
 * @interface
 */
export interface ShiftRequirementFormData {
  name: string
  day_of_week: number
  start_time: string
  end_time: string
  required_count: number
}

/**
 * Represents an assigned shift to an employee
 * Links an employee to a shift requirement on a specific date
 * @interface
 */
export interface ShiftAssignment {
  id: string
  employee_id: string
  shift_requirement_id: string
  date: string
}

/**
 * Represents a single day in the schedule
 * Contains all shifts and their assignments for that day
 * @interface
 */
export interface ScheduleDay {
  date: string
  shifts: {
    requirement: ShiftRequirement
    assignments: {
      id: string
      employee: {
        id: string
        full_name: string
      }
    }[]
  }[]
}

/**
 * Represents a complete weekly schedule
 * Contains an array of schedule days and the date range
 * @interface
 */
export interface WeeklySchedule {
  startDate: string
  endDate: string
  days: ScheduleDay[]
} 